apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-deployment
  labels:
    app: clock
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: clock
  template:
    metadata:
      labels:
        app: clock
    spec:
      containers:
      - name: clock
        image: safernandez666/clock:$JOB_NAME-$BUILD_NUMBER 
        ports:
        - containerPort: 8080
        imagePullPolicy: "Always"
---

apiVersion: v1
kind: Service
metadata:
  name: clock-service
spec:
  type: LoadBalancer 
  ports:
    - name: http
      port: 8080
  selector:
    app: clock